[features]
seeds = true
skip-lint = false
[programs.localnet]
account_test = "2SAUzLPDFwkedHtamM19uvC2BC12y6VKsoW2a91bR2KZ"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/austin/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
